const NAV=[['dashboard','dashboard','📊','Dashboard'],['mesas','mesas','🪑','Mesas'],['menu','menu','🍽️','Menú'],['pedidos','pedidos','📝','Pedidos'],['cocina','cocina','👨‍🍳','Cocina'],['caja','caja','💳','Caja'],['reportes','reportes','📈','Reportes']];
function prefix(){return location.pathname.includes('/modulos/')?'../../':''}
function renderShell(active,title,breadcrumb){const p=prefix();const sb=document.getElementById('sidebar');if(sb)sb.innerHTML=`<div class="brand"><div class="brand-mark">🍽️</div><div><div class="brand-name">RestaurantePro</div><div class="brand-sub">Sistema de Gestión</div></div></div><div class="nav-section">Menú principal</div>${NAV.map(n=>`<a class="nav-link ${n[0]===active?'active':''}" href="${p}modulos/${n[1]}/${n[1]}.html"><span class="icon">${n[2]}</span>${n[3]}</a>`).join('')}<div class="user-card"><div class="name">Administrador</div><div class="role">Sin login</div><button class="btn btn-outline btn-sm" style="width:100%;margin-top:12px" onclick="limpiarDatos()">Limpiar datos</button></div>`;const h=document.getElementById('header');if(h)h.innerHTML=`<div style="display:flex;align-items:center;gap:14px"><button class="mobile-toggle btn btn-outline btn-sm" onclick="document.getElementById('sidebar').classList.toggle('open')">☰</button><div><div class="crumb">${breadcrumb}</div><h1>${title}</h1></div></div><div class="header-right"><div class="pill">SIN LOGIN</div><div class="user-chip"><div class="avatar">A</div><div class="meta"><div class="name">Administrador</div><div class="role">Administrador</div></div></div></div>`}
function limpiarDatos(){if(confirm('¿Limpiar todos los datos registrados?')){DB.clear();location.reload()}}
function fmt(n){return 'S/ '+Number(n||0).toFixed(2)}
function shortDate(iso){return new Date(iso).toLocaleString('es-PE',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}
function uid(){return Date.now()+Math.floor(Math.random()*999)}
function openModal(id){document.getElementById(id)?.classList.add('show')}
function closeModal(id){document.getElementById(id)?.classList.remove('show')}
document.addEventListener('click',e=>{if(e.target.classList.contains('modal-overlay'))e.target.classList.remove('show')})
function toast(type,title,body=''){let w=document.querySelector('.toast-wrap');if(!w){w=document.createElement('div');w.className='toast-wrap';document.body.appendChild(w)}const el=document.createElement('div');el.className=`toast ${type}`;el.innerHTML=`<b>${title}</b>${body?`<div style="color:#64748b;font-size:13px;margin-top:3px">${body}</div>`:''}`;w.appendChild(el);setTimeout(()=>el.remove(),3200)}
function estadoBadge(e){const map={Disponible:'success',Ocupada:'danger',Reservada:'warning','En limpieza':'info',Activo:'success',Inactivo:'muted',Pendiente:'warning','En preparación':'info',Listo:'success',Entregado:'primary',Pagado:'success'};return `<span class="badge ${map[e]||'muted'}">${e}</span>`}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
