let cart=[];
function renderPedidos(){const pedidos=DB.get(DB_KEYS.PEDIDOS)||[];const tabla=document.getElementById('pedidosTable');if(!tabla)return;if(!pedidos.length){tabla.innerHTML='<div class="empty"><h3>No hay pedidos registrados</h3><p>Primero crea una mesa, luego un plato activo, y después registra el pedido.</p></div>';return}tabla.innerHTML=`<table class="tbl"><thead><tr><th>#</th><th>Mesa</th><th>Items</th><th>Total</th><th>Estado</th><th>Fecha</th><th>Acciones</th></tr></thead><tbody>${[...pedidos].reverse().map(p=>`<tr><td><b>#${p.id}</b></td><td>Mesa ${p.mesaId}</td><td>${p.items.length} platos</td><td><b>${fmt(p.total)}</b></td><td>${estadoBadge(p.estado)}</td><td style="font-size:12px;color:var(--muted)">${shortDate(p.fecha)}</td><td><div style="display:flex;gap:6px;flex-wrap:wrap"><button class="btn btn-sm btn-outline" onclick="verPedido(${p.id})">Ver</button><button class="btn btn-sm btn-outline" onclick="cambiarEstadoPedido(${p.id})">Estado</button><button class="btn btn-sm btn-danger" onclick="eliminarPedido(${p.id})">Eliminar</button></div></td></tr>`).join('')}</tbody></table>`}
function openNuevoPedido(){cart=[];const mesas=DB.get(DB_KEYS.MESAS)||[];const menu=DB.get(DB_KEYS.MENU)||[];if(!mesas.length){alert('Primero registra una mesa en el módulo Mesas.');return}if(!menu.length){alert('Primero registra platos en el módulo Menú.');return}const mesasDisp=mesas.filter(m=>m.estado==='Disponible'||m.estado==='Ocupada');if(!mesasDisp.length){alert('No hay mesas disponibles u ocupadas para crear pedidos.');return}document.getElementById('selMesa').innerHTML='<option value="">Seleccionar mesa</option>'+mesasDisp.map(m=>`<option value="${m.id}">Mesa ${m.numero} - ${m.capacidad} personas - ${m.estado}</option>`).join('');renderPlatosSeleccion();renderCart();openModal('pedidoModal')}
function renderPlatosSeleccion(){const activos=(DB.get(DB_KEYS.MENU)||[]).filter(p=>p.estado==='Activo'&&Number(p.stock)>0);const c=document.getElementById('platosSel');if(!activos.length){c.innerHTML='<p class="empty">No hay platos activos con stock.</p>';return}c.innerHTML=activos.map(p=>`<div class="cart-item" onclick="addToCart(${p.id})" style="cursor:pointer"><div><div class="nm">${p.icono||'🍽️'} ${p.nombre}</div><div class="pr">${p.categoria} · Stock: ${p.stock}</div></div><strong>${fmt(p.precio)}</strong><button class="btn btn-sm btn-primary" type="button">+</button></div>`).join('')}
function addToCart(id){const plato=(DB.get(DB_KEYS.MENU)||[]).find(p=>Number(p.id)===Number(id));if(!plato)return;let item=cart.find(i=>Number(i.platoId)===Number(id));if(item){if(item.cant>=Number(plato.stock)){alert('No hay más stock disponible.');return}item.cant++}else cart.push({platoId:plato.id,nombre:plato.nombre,precio:Number(plato.precio),cant:1});renderCart()}
function changeQty(id,delta){const item=cart.find(i=>Number(i.platoId)===Number(id));const plato=(DB.get(DB_KEYS.MENU)||[]).find(p=>Number(p.id)===Number(id));if(!item)return;if(delta>0&&plato&&item.cant>=Number(plato.stock)){alert('No hay más stock disponible.');return}item.cant+=delta;if(item.cant<=0)cart=cart.filter(i=>Number(i.platoId)!==Number(id));renderCart()}
function renderCart(){const list=document.getElementById('cartList'),tot=document.getElementById('cartTotals');if(!cart.length)list.innerHTML='<p style="text-align:center;padding:30px;color:var(--muted)">Aún no hay platos seleccionados</p>';else list.innerHTML=cart.map(i=>`<div class="cart-item"><div><div class="nm">${i.nombre}</div><div class="pr">${fmt(i.precio)} c/u</div></div><div class="qty"><button type="button" onclick="changeQty(${i.platoId},-1)">−</button><b>${i.cant}</b><button type="button" onclick="changeQty(${i.platoId},1)">+</button></div><b>${fmt(i.precio*i.cant)}</b></div>`).join('');const total=cart.reduce((a,i)=>a+i.precio*i.cant,0);tot.innerHTML=`<div class="row"><span>Subtotal</span><span>${fmt(total)}</span></div><div class="row"><span>IGV incluido</span><span>${fmt(total*.18)}</span></div><div class="row grand"><span>Total</span><span>${fmt(total)}</span></div>`}
function guardarPedido(){const mesaId=Number(document.getElementById('selMesa').value);if(!mesaId){alert('Selecciona una mesa.');return}if(!cart.length){alert('Agrega al menos un plato.');return}let pedidos=DB.get(DB_KEYS.PEDIDOS)||[],mesas=DB.get(DB_KEYS.MESAS)||[],menu=DB.get(DB_KEYS.MENU)||[];const total=cart.reduce((a,i)=>a+i.precio*i.cant,0);const nuevo={id:uid(),mesaId,mozo:'Administrador',estado:'Pendiente',items:[...cart],subtotal:total,total,fecha:new Date().toISOString()};pedidos.push(nuevo);DB.set(DB_KEYS.PEDIDOS,pedidos);const mi=mesas.findIndex(m=>Number(m.id)===mesaId);if(mi>=0){mesas[mi].estado='Ocupada';DB.set(DB_KEYS.MESAS,mesas)}cart.forEach(it=>{const pi=menu.findIndex(p=>Number(p.id)===Number(it.platoId));if(pi>=0)menu[pi].stock=Math.max(0,Number(menu[pi].stock)-Number(it.cant))});DB.set(DB_KEYS.MENU,menu);closeModal('pedidoModal');toast('success','Pedido registrado','El pedido fue enviado a cocina.');renderPedidos()}
function verPedido(id){const p=(DB.get(DB_KEYS.PEDIDOS)||[]).find(x=>Number(x.id)===Number(id));if(!p)return;document.getElementById('detModalBody').innerHTML=`<div class="row" style="margin-bottom:14px"><div><b style="font-size:18px">Pedido #${p.id}</b><br><small>Mesa ${p.mesaId}</small></div>${estadoBadge(p.estado)}</div><table class="tbl"><thead><tr><th>Plato</th><th>Cant</th><th>P. Unit</th><th>Subtotal</th></tr></thead><tbody>${p.items.map(i=>`<tr><td>${i.nombre}</td><td>${i.cant}</td><td>${fmt(i.precio)}</td><td><b>${fmt(i.precio*i.cant)}</b></td></tr>`).join('')}</tbody></table><div style="text-align:right;font-size:20px;font-weight:950;margin-top:14px">Total: ${fmt(p.total)}</div>`;openModal('detPedidoModal')}
function cambiarEstadoPedido(id){const orden=['Pendiente','En preparación','Listo','Entregado','Pagado'];let pedidos=DB.get(DB_KEYS.PEDIDOS)||[];const i=pedidos.findIndex(p=>Number(p.id)===Number(id));if(i<0)return;pedidos[i].estado=orden[(orden.indexOf(pedidos[i].estado)+1)%orden.length];DB.set(DB_KEYS.PEDIDOS,pedidos);renderPedidos()}
function eliminarPedido(id){if(!confirm('¿Eliminar este pedido?'))return;DB.set(DB_KEYS.PEDIDOS,(DB.get(DB_KEYS.PEDIDOS)||[]).filter(p=>Number(p.id)!==Number(id)));renderPedidos()}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('btnNuevoPedido')?.addEventListener('click',openNuevoPedido)});
